[build]
target = "x86_64-win7-windows-msvc"

[target.x86_64-win7-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "-C", "control-flow-guard", "-L", "native=C:/tmp/octane-launcher/winlibs"]

[unstable]
build-std = ["std", "panic_abort"]
